kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-0904
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: test-0904
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: test-0904
    spec:
      containers:
        - name: main
          image: nginx
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: COMPONENT_ID
              value: {{PROJECT_ID}}         
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
